import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Sparkles, X } from "lucide-react";
import { useEffect, useState } from "react";
import { createTask, listTasks } from "../services/tasks";
import { listProjectMembers, listProjects } from "../services/projects";
import { requestRocketAI, type AIFeature, type RocketAIResponse } from "../services/ai";
import { useRocketAIStore } from "../stores/rocketAIStore";
import { Alert, Badge, Button, Spinner } from "./ui";

const features: Array<[AIFeature, string]> = [["create_task", "자연어 Task 생성"], ["decompose_tasks", "Task 분해"], ["briefing", "오늘의 브리핑"], ["project_summary", "프로젝트 요약"], ["weekly_report", "주간 보고서"], ["project_qa", "프로젝트 Q&A"], ["github_summary", "GitHub 요약"]];

export function RocketAIPanel() {
  const opened = useRocketAIStore((state) => state.opened);
  const close = useRocketAIStore((state) => state.close);
  const queryClient = useQueryClient();
  const projects = useQuery({ queryKey: ["projects"], queryFn: listProjects, enabled: opened });
  const [projectId, setProjectId] = useState("");
  const [feature, setFeature] = useState<AIFeature>("create_task");
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState<RocketAIResponse | null>(null);
  const tasks = useQuery({ queryKey: ["tasks", projectId], queryFn: () => listTasks(projectId), enabled: opened && Boolean(projectId) });
  const members = useQuery({ queryKey: ["members", projectId], queryFn: () => listProjectMembers(projectId), enabled: opened && Boolean(projectId) });
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projectId, projects.data]);
  const ask = useMutation({ mutationFn: () => requestRocketAI({ projectId, feature, prompt: prompt.trim(), context: { project: (() => { const selected = projects.data?.find((item) => item.id === projectId); return selected ? { name: selected.name, status: selected.status, repositoryConnected: Boolean(selected.github_repository_url) } : null; })(), members: members.data?.map((member) => ({ id: member.user_id, name: member.profile?.name, studentId: member.profile?.student_id })) ?? [], tasks: tasks.data?.slice(0, 100).map((task) => ({ id: task.id, title: task.title, description: task.description, status: task.status, priority: task.priority, dueDate: task.due_date, progress: task.progress, assigneeIds: task.task_assignees?.map((item) => item.user_id) ?? [] })) ?? [] } }), onSuccess: setResult });
  const apply = useMutation({ mutationFn: async () => { if (!result || result.kind !== "task_proposal") return; for (const task of result.tasks) await createTask({ projectId, title: task.title, description: task.description, priority: task.priority, dueDate: task.dueDate ?? undefined, assigneeIds: task.assigneeIds }); }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["tasks", projectId] }); setResult(null); setPrompt(""); } });
  if (!opened) return null;
  return <div className="fixed inset-0 z-[80] flex justify-end"><button aria-label="Rocket AI 닫기" className="absolute inset-0 bg-slate-950/45" onClick={close} /><aside role="dialog" aria-modal="true" aria-label="Rocket AI" className="relative h-full w-full max-w-xl overflow-y-auto border-l border-line bg-surface p-5 shadow-lift sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Sparkles className="text-brand" /><h2 className="text-xl font-extrabold text-ink">Rocket AI</h2></div><Button variant="ghost" className="h-9 w-9 p-0" onClick={close}><X size={18} /></Button></div><p className="mt-2 text-sm text-muted">AI 제안은 확인 전까지 프로젝트를 변경하지 않습니다.</p><label className="label mt-6" htmlFor="ai-project">프로젝트</label><select id="ai-project" className="field" value={projectId} onChange={(event) => { setProjectId(event.target.value); setResult(null); }}>{projects.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="label mt-4" htmlFor="ai-feature">기능</label><select id="ai-feature" className="field" value={feature} onChange={(event) => { setFeature(event.target.value as AIFeature); setResult(null); }}>{features.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label className="label mt-4" htmlFor="ai-prompt">요청</label><textarea id="ai-prompt" className="field min-h-28" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="예: 다음 주 금요일까지 로그인 E2E 테스트를 맡겨줘" /><Button className="mt-3 w-full" disabled={!projectId || !prompt.trim() || ask.isPending} onClick={() => ask.mutate()}>{ask.isPending ? <Spinner className="h-4 w-4" /> : <Sparkles size={16} />} 분석</Button>{ask.error && <Alert className="mt-4">{ask.error.message}</Alert>}{result && <section className="mt-5 rounded-2xl border border-line bg-raised p-4"><div className="flex items-center justify-between"><h3 className="font-extrabold text-ink">AI 제안</h3><Badge tone={result.kind === "task_proposal" ? "blue" : "neutral"}>{result.kind === "task_proposal" ? "확인 필요" : "답변"}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-ink">{result.summary}</p>{result.tasks.map((task, index) => <article key={`${task.title}-${index}`} className="mt-3 rounded-xl border border-line bg-surface p-3"><div className="font-bold text-ink">{task.title}</div><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-muted">{task.description}</p><div className="mt-2 flex gap-2"><Badge>{task.priority}</Badge>{task.dueDate && <Badge>{task.dueDate}</Badge>}</div></article>)}{result.kind === "task_proposal" && <Button className="mt-4 w-full" disabled={apply.isPending || !result.tasks.length} onClick={() => apply.mutate()}>{apply.isPending ? <Spinner className="h-4 w-4" /> : <Check size={16} />} 이 내용으로 Task 생성</Button>}{apply.error && <Alert className="mt-3">{apply.error.message}</Alert>}</section>}</aside></div>;
}
