import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ChevronDown, MessageSquarePlus, Minus, Send, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState, type KeyboardEvent } from "react";
import { useLocation } from "react-router-dom";
import { listAIModels, requestRocketAI, type AIConversationMessage, type AIFeature, type RocketAIResponse } from "../services/ai";
import { listProjectMembers, listProjects } from "../services/projects";
import { createTask, listTasks } from "../services/tasks";
import { useRocketAIStore } from "../stores/rocketAIStore";
import { Alert, Badge, Button, Spinner } from "./ui";

const features: Array<[AIFeature, string]> = [["create_task", "Task 생성"], ["decompose_tasks", "Task 분해"], ["briefing", "오늘 브리핑"], ["project_summary", "프로젝트 요약"], ["weekly_report", "주간 보고"], ["project_qa", "프로젝트 Q&A"], ["github_summary", "GitHub 요약"]];
interface ChatMessage extends AIConversationMessage { id: string; model?: string; proposal?: RocketAIResponse }

export function RocketAIPanel() {
  const { pathname } = useLocation();
  const opened = useRocketAIStore((state) => state.opened);
  const minimized = useRocketAIStore((state) => state.minimized);
  const open = useRocketAIStore((state) => state.open);
  const close = useRocketAIStore((state) => state.close);
  const minimize = useRocketAIStore((state) => state.minimize);
  const queryClient = useQueryClient();
  const projects = useQuery({ queryKey: ["projects"], queryFn: listProjects, enabled: opened });
  const models = useQuery({ queryKey: ["ai-models"], queryFn: listAIModels, enabled: opened });
  const routeProjectId = pathname.match(/^\/projects\/([0-9a-f-]{36})(?:\/|$)/iu)?.[1] ?? "";
  const [projectId, setProjectId] = useState("");
  const [modelId, setModelId] = useState(() => localStorage.getItem("rocket-ai:model") ?? "");
  const [feature, setFeature] = useState<AIFeature>("project_qa");
  const [prompt, setPrompt] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const tasks = useQuery({ queryKey: ["tasks", projectId], queryFn: () => listTasks(projectId), enabled: opened && Boolean(projectId) });
  const members = useQuery({ queryKey: ["members", projectId], queryFn: () => listProjectMembers(projectId), enabled: opened && Boolean(projectId) });
  useEffect(() => { if (routeProjectId && projects.data?.some((item) => item.id === routeProjectId)) setProjectId(routeProjectId); else if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projectId, projects.data, routeProjectId]);
  useEffect(() => { if (!models.data?.length) return; const chosen = models.data.some((item) => item.id === modelId) ? modelId : (models.data.find((item) => item.isDefault)?.id ?? models.data[0]!.id); setModelId(chosen); localStorage.setItem("rocket-ai:model", chosen); }, [modelId, models.data]);
  const context = useMemo(() => ({ project: projects.data?.find((item) => item.id === projectId) ? { name: projects.data.find((item) => item.id === projectId)!.name, status: projects.data.find((item) => item.id === projectId)!.status } : null, members: members.data?.map((member) => ({ id: member.user_id, name: member.profile?.name, studentId: member.profile?.student_id })) ?? [], tasks: tasks.data?.slice(0, 100).map((task) => ({ id: task.id, title: task.title, description: task.description, status: task.status, priority: task.priority, dueDate: task.due_date, progress: task.progress, assigneeIds: task.task_assignees?.map((item) => item.user_id) ?? [] })) ?? [] }), [members.data, projectId, projects.data, tasks.data]);
  const ask = useMutation({ mutationFn: async () => { const userMessage: ChatMessage = { id: crypto.randomUUID(), role: "user", content: prompt.trim() }; const recent = [...messages, userMessage].slice(-20).map(({ role, content }) => ({ role, content })); setMessages((value) => [...value, userMessage]); setPrompt(""); const result = await requestRocketAI({ projectId, modelSettingId: modelId, feature, messages: recent, context }); return result; }, onSuccess: (result) => setMessages((value) => [...value, { id: crypto.randomUUID(), role: "assistant", content: result.summary, model: result.model.displayName, proposal: result }]) });
  const apply = useMutation({ mutationFn: async (proposal: RocketAIResponse) => { if (proposal.kind !== "task_proposal" || !window.confirm(`${proposal.tasks.length}개 Task를 생성할까요?`)) return; for (const task of proposal.tasks) await createTask({ projectId, title: task.title, description: task.description, priority: task.priority, dueDate: task.dueDate ?? undefined, assigneeIds: task.assigneeIds }); }, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["tasks", projectId] }); } });
  const submit = () => { if (projectId && modelId && prompt.trim() && !ask.isPending) ask.mutate(); };
  const keyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } };
  if (!opened) return null;
  if (minimized) return <button onClick={open} className="fixed bottom-5 right-5 z-[70] flex items-center gap-2 rounded-full bg-brand px-4 py-3 text-sm font-bold text-white shadow-lift"><Sparkles size={18} /> Rocket AI</button>;
  return <aside aria-label="Rocket AI" className="fixed bottom-4 right-4 z-[70] flex h-[min(680px,calc(100vh-2rem))] w-[min(420px,calc(100vw-2rem))] flex-col overflow-hidden rounded-3xl border border-line bg-surface shadow-2xl">
    <header className="flex items-center justify-between border-b border-line px-4 py-3"><div className="flex items-center gap-2"><Sparkles size={18} className="text-brand" /><div><h2 className="text-sm font-extrabold text-ink">Rocket AI</h2><p className="text-[10px] text-muted">제안은 확인 후에만 적용됩니다.</p></div></div><div className="flex"><Button variant="ghost" className="h-8 w-8 p-0" title="새 대화" onClick={() => setMessages([])}><MessageSquarePlus size={16} /></Button><Button variant="ghost" className="h-8 w-8 p-0" title="최소화" onClick={minimize}><Minus size={16} /></Button><Button variant="ghost" className="h-8 w-8 p-0" title="닫기" onClick={close}><X size={16} /></Button></div></header>
    <div className="grid grid-cols-2 gap-2 border-b border-line p-3"><label className="sr-only" htmlFor="ai-project">프로젝트</label><select id="ai-project" className="field h-9 text-xs" value={projectId} onChange={(event) => setProjectId(event.target.value)}>{projects.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="sr-only" htmlFor="ai-model">모델</label><div className="relative"><select id="ai-model" className="field h-9 appearance-none pr-7 text-xs" value={modelId} onChange={(event) => { setModelId(event.target.value); localStorage.setItem("rocket-ai:model", event.target.value); }}>{(["openai", "anthropic", "google"] as const).map((provider) => <optgroup key={provider} label={provider}>{models.data?.filter((item) => item.provider === provider).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</optgroup>)}</select><ChevronDown className="pointer-events-none absolute right-2 top-2.5 text-muted" size={14} /></div><label className="sr-only" htmlFor="ai-feature">기능</label><select id="ai-feature" className="field col-span-2 h-9 text-xs" value={feature} onChange={(event) => setFeature(event.target.value as AIFeature)}>{features.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
    <div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.length === 0 && <div className="rounded-2xl bg-raised p-4 text-sm leading-6 text-muted">프로젝트 맥락을 바탕으로 질문하거나 Task 제안을 요청하세요.</div>}{messages.map((message) => <div key={message.id} className={message.role === "user" ? "ml-8 rounded-2xl rounded-br-md bg-brand p-3 text-sm text-white" : "mr-4 rounded-2xl rounded-bl-md border border-line bg-raised p-3 text-sm text-ink"}><p className="whitespace-pre-wrap leading-6">{message.content}</p>{message.model && <p className="mt-2 text-[10px] text-muted">{message.model}</p>}{message.proposal?.tasks.map((task, index) => <article key={`${task.title}-${index}`} className="mt-2 rounded-xl border border-line bg-surface p-2.5"><p className="font-bold">{task.title}</p><div className="mt-1 flex gap-1"><Badge>{task.priority}</Badge>{task.dueDate && <Badge>{task.dueDate}</Badge>}</div></article>)}{message.proposal?.kind === "task_proposal" && <Button size="sm" className="mt-3 w-full" disabled={apply.isPending} onClick={() => apply.mutate(message.proposal!)}><Check size={14} /> Task 생성 확인</Button>}</div>)}{ask.isPending && <div className="mr-24 rounded-2xl bg-raised p-3"><Spinner className="h-4 w-4" /></div>}{(ask.error || models.error || apply.error) && <Alert>{ask.error?.message ?? models.error?.message ?? apply.error?.message}</Alert>}</div>
    <footer className="border-t border-line p-3"><p className="mb-2 truncate text-[10px] font-semibold text-muted">현재 프로젝트: {projects.data?.find((item) => item.id === projectId)?.name ?? "선택 안 됨"}</p><div className="flex items-end gap-2"><textarea aria-label="Rocket AI 메시지" className="field max-h-28 min-h-11 resize-none py-2.5 text-sm" value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={keyDown} placeholder="메시지 입력 · Shift+Enter 줄바꿈" /><Button className="h-11 w-11 shrink-0 p-0" disabled={!projectId || !modelId || !prompt.trim() || ask.isPending} onClick={submit}><Send size={16} /></Button></div></footer>
  </aside>;
}
